name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Container-Build-FizzBuzz:
    strategy:
      matrix:
        os: [[self-hosted, linux, ARM64]] #, [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image with Buildah
      uses: redhat-actions/buildah-build@v2
      with: 
        image: fizzbuzz
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Run the Docker image
      run: podman run fizzbuzz.${{ github.sha }}
