name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Container-Build-FizzBuzz:
    strategy:
      matrix:
        os: [ubuntu-latest, [self-hosted, linux, ARM64]]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fizzbuzz.${{ github.sha }}
    - name: Run the Docker image
      run: docker run fizzbuzz.${{ github.sha }}
