name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  x86-fizzbuzz-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fizzbuzz:latest
    - name: Run the Docker image
      run: docker run fizzbuzz

  aarch64-fizzbuzz-container:
    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image with Buildah
      uses: redhat-actions/buildah-build@v2
      with: 
        image: fizzbuzz
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Run the Docker image
      run: podman run fizzbuzz

